{
 "title": "MinIO Overview",
 "description": "MinIO dashboard - https://min.io/",
 "tags": [ "uitstor" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(uitstor_node_process_starttime_seconds{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (uitstor_s3_traffic_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Usable Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(uitstor_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(uitstor_bucket_usage_total_bytes{job=\"$scrape_jobs\"}) by (instance)",
     "legendFormat": "Used Capacity"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (range) (uitstor_bucket_objects_size_distribution{job=\"$scrape_jobs\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (uitstor_node_file_descriptor_open_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (uitstor_s3_traffic_sent_bytes{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (uitstor_node_go_routine_total{job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "uitstor_cluster_nodes_online_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Online Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "uitstor_cluster_disk_online_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Total online disks in MinIO Cluster"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bucket) (uitstor_bucket_usage_total_bytes{job=\"$scrape_jobs\"}))"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(uitstor_s3_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(uitstor_s3_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "uitstor_cluster_nodes_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Total Offline Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "uitstor_cluster_disk_offline_total{job=\"$scrape_jobs\"}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(uitstor_bucket_usage_object_total{job=\"$scrape_jobs\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Time Since Last Heal Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uitstor_heal_time_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uitstor_usage_last_activity_nano_seconds{job=\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(uitstor_s3_requests_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(uitstor_s3_requests_errors_total{job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Sent Bytes for Replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (server) (uitstor_bucket_replication_sent_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "replication sent bytes [{{server}}]"
    }
   ]
  },
  {
   "title": "Received Bytes for Replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by (server) (uitstor_bucket_replication_received_bytes{job=\"$scrape_jobs\"})",
     "legendFormat": "replication received bytes [{{server}}]"
    }
   ]
  },
  {
   "title": "Internode Data Transfer",
   "type": "graph",
   "description": "Total number of bytes received and sent among all MinIO server instances",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(uitstor_inter_node_traffic_sent_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "rate(uitstor_inter_node_traffic_received_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Healing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (uitstor_heal_objects_heal_total{job=\"$scrape_jobs\"})",
     "legendFormat": "Objects healed in current self heal run"
    },
    {
     "expr": "sum by (instance) (uitstor_heal_objects_error_total{job=\"$scrape_jobs\"})",
     "legendFormat": "Heal errors in current self heal run"
    },
    {
     "expr": "sum by (instance) (uitstor_heal_objects_total{job=\"$scrape_jobs\"}) ",
     "legendFormat": "Objects scanned in current self heal run"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(uitstor_node_process_cpu_total_seconds{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "CPU Usage Rate [{{server}}]"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "uitstor_node_process_resident_memory_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Memory Used [{{server}}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "uitstor_node_disk_used_bytes{job=\"$scrape_jobs\"}",
     "legendFormat": "Used Capacity [{{server}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Drives Free Inodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "uitstor_cluster_disk_free_inodes{job=\"$scrape_jobs\"}",
     "legendFormat": "Free Inodes [{{server}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "graph",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(uitstor_node_syscall_read_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(uitstor_node_syscall_write_total{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Node File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "uitstor_node_file_descriptor_open_total{job=\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(uitstor_node_io_rchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(uitstor_node_io_wchar_bytes{job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  }
 ]
}