{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "uitstor.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "uitstor.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "uitstor.name" . }}
    chart: {{ template "uitstor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "uitstor.name" . }}
      release: {{ .Release.Name }}
  ingress:
    - ports:
        - port: {{ .Values.uitstorAPIPort }}
        - port: {{ .Values.uitstorConsolePort }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "uitstor.name" . }}-client: "true"
      {{- end }}
{{- end }}
