{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: uitstor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "uitstor.name" . }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "uitstor.name" . }}
{{- end }}