{{- $global := . -}}
{{- if .Values.users }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "uitstor.fullname" . }}-make-user-job
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "uitstor.name" . }}-make-user-job
    chart: {{ template "uitstor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- with .Values.makeUserJob.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "uitstor.name" . }}-job
        release: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.makeUserJob.podAnnotations }}
      annotations:
{{ toYaml .Values.makeUserJob.podAnnotations | indent 8 }}
{{- end }}
    spec:
      restartPolicy: OnFailure
{{- include "uitstor.imagePullSecrets" . | indent 6 }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.makeUserJob.nodeSelector | indent 8 }}
{{- end }}
{{- with .Values.makeUserJob.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.makeUserJob.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.makeUserJob.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.makeUserJob.securityContext.runAsUser }}
        runAsGroup: {{ .Values.makeUserJob.securityContext.runAsGroup }}
        fsGroup: {{ .Values.makeUserJob.securityContext.fsGroup }}
{{- end }}
      volumes:
        - name: uitstor-configuration
          projected:
            sources:
            - configMap:
                name: {{ template "uitstor.fullname" . }}
            - secret:
                name: {{ template "uitstor.secretName" . }}
            {{- range .Values.users }}
            {{- if .existingSecret }}
            - secret:
                name: {{ tpl .existingSecret $global }}
                items:
                  - key: {{ .existingSecretKey }}
                    path: secrets/{{ tpl .accessKey $global }}
            {{- end }}
            {{- end }}
        {{- if .Values.tls.enabled }}
        - name: cert-secret-volume-mc
          secret:
            secretName: {{ .Values.tls.certSecret }}
            items:
            - key: {{ .Values.tls.publicCrt }}
              path: CAs/public.crt
        {{ end }}
      containers:
      - name: uitstor-mc
        image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
        imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
        command: ["/bin/sh", "/config/add-user"]
        env:
          - name: MINIO_ENDPOINT
            value: {{ template "uitstor.fullname" . }}
          - name: MINIO_PORT
            value: {{ .Values.service.port | quote }}
        volumeMounts:
          - name: uitstor-configuration
            mountPath: /config
          {{- if .Values.tls.enabled }}
          - name: cert-secret-volume-mc
            mountPath: {{ .Values.configPathmc }}certs
          {{ end }}
        resources:
{{ toYaml .Values.makeUserJob.resources | indent 10 }}
{{- end }}
