{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "uitstor.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "uitstor.name" . }}
    chart: {{ template "uitstor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  rootUser: {{ include "uitstor.root.username" . | b64enc | quote }}
  rootPassword: {{ include "uitstor.root.password" . | b64enc | quote }}
  {{- if .Values.etcd.clientCert }}
  etcd_client.crt: {{ .Values.etcd.clientCert | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.etcd.clientCertKey }}
  etcd_client.key: {{ .Values.etcd.clientCertKey | toString | b64enc | quote }}
  {{- end }}
{{- end }}
