version: '3.7'

# Settings and configurations that are common for all containers
x-uitstor-common: &uitstor-common
  image: quay.io/uitstor/uitstor:RELEASE.2022-07-17T15-43-14Z
  command: server --console-address ":9001" http://uitstor{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: uitstoradmin
    # MINIO_ROOT_PASSWORD: uitstoradmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/uitstor/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running uitstor server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  uitstor1:
    <<: *uitstor-common
    hostname: uitstor1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  uitstor2:
    <<: *uitstor-common
    hostname: uitstor2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  uitstor3:
    <<: *uitstor-common
    hostname: uitstor3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  uitstor4:
    <<: *uitstor-common
    hostname: uitstor4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - uitstor1
      - uitstor2
      - uitstor3
      - uitstor4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
