apiVersion: v1
description: Multi-Cloud Object Storage
name: uitstor
version: 4.0.5
appVersion: RELEASE.2022-05-08T23-50-31Z
keywords:
  - uitstor
  - storage
  - object-storage
  - s3
  - cluster
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@uitstor.io
